import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Rouge à Lèvres Bio",
    price: "5000 FCFA",
    category: "Cosmétiques",
    image: "/placeholder.svg?height=400&width=400",
    description: "Rouge à lèvres bio aux pigments naturels pour des lèvres éclatantes.",
    longDescription:
      "Ce rouge à lèvres bio est formulé avec des ingrédients naturels et biologiques de haute qualité. Enrichi en huiles végétales nourrissantes, il hydrate vos lèvres tout en leur apportant une couleur intense et durable. Sa texture crémeuse glisse parfaitement sur les lèvres pour une application facile et un fini satiné élégant. Sans parabènes, sans phtalates et non testé sur les animaux, ce rouge à lèvres respecte votre peau et l'environnement.",
    features: [
      "Formule bio et naturelle",
      "Hydratant",
      "Longue tenue",
      "Non testé sur les animaux",
      "Fabriqué en France",
    ],
    colors: ["Rose", "Rouge", "Corail", "Bordeaux"],
    inStock: true,
  },
  {
    id: "2",
    name: "Mascara Volumisant",
    price: "6500 FCFA",
    category: "Cosmétiques",
    image: "/placeholder.svg?height=400&width=400",
    description: "Mascara volumisant pour des cils épais et allongés.",
    longDescription:
      "Notre mascara volumisant est spécialement conçu pour donner du volume et de la longueur à vos cils. Sa formule enrichie en kératine et en vitamines renforce les cils tout en les nourrissant. Le pinceau exclusif sépare parfaitement les cils et évite les paquets pour un regard intense et défini. Résistant à l'eau et à la chaleur, ce mascara tient toute la journée sans couler ni s'effriter. Pour un regard captivant en un seul geste !",
    features: ["Volumisant", "Allongeant", "Formule enrichie en kératine", "Résistant à l'eau", "Tenue 24h"],
    colors: ["Noir", "Brun", "Bleu nuit"],
    inStock: true,
  },
  {
    id: "3",
    name: "Robe d'Été Fleurie",
    price: "15000 FCFA",
    category: "Vêtements",
    image: "/placeholder.svg?height=400&width=400",
    description: "Robe légère à motifs floraux, parfaite pour l'été.",
    longDescription:
      "Cette magnifique robe d'été est confectionnée dans un tissu léger et fluide qui vous garantit un confort optimal même pendant les journées les plus chaudes. Son imprimé floral délicat et ses finitions soignées en font une pièce à la fois élégante et décontractée. La coupe évasée met en valeur votre silhouette tout en offrant une grande liberté de mouvement. Idéale pour une promenade en ville, un déjeuner entre amis ou une soirée d'été.",
    features: ["100% coton", "Doublure intégrée", "Poches latérales", "Lavable en machine", "Fabriquée éthiquement"],
    colors: ["Bleu ciel", "Rose pâle", "Blanc", "Vert menthe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "4",
    name: "Chemisier en Soie",
    price: "12000 FCFA",
    category: "Vêtements",
    image: "/placeholder.svg?height=400&width=400",
    description: "Chemisier élégant en soie, idéal pour le bureau ou les sorties.",
    longDescription:
      "Ce chemisier en soie véritable incarne l'élégance intemporelle. Sa coupe fluide et sa finition impeccable en font une pièce polyvalente qui s'adapte aussi bien à une tenue de bureau qu'à une sortie en ville. Le tissu soyeux offre une sensation de luxe contre la peau et une durabilité exceptionnelle. Les boutons nacrés et les finitions soignées témoignent de l'attention portée aux détails. Un basique de garde-robe qui ne se démode jamais.",
    features: [
      "100% soie naturelle",
      "Boutons nacrés",
      "Col classique",
      "Nettoyage à sec recommandé",
      "Fabrication artisanale",
    ],
    colors: ["Blanc", "Noir", "Bleu marine", "Bordeaux"],
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "5",
    name: "Casserole Antiadhésive",
    price: "8000 FCFA",
    category: "Ustensiles",
    image: "/placeholder.svg?height=400&width=400",
    description: "Casserole antiadhésive de haute qualité pour une cuisine saine.",
    longDescription:
      "Notre casserole antiadhésive premium est conçue pour les cuisiniers exigeants. Son revêtement antiadhésif de dernière génération permet une cuisson sans matière grasse et un nettoyage facile. Le fond à triple épaisseur assure une répartition homogène de la chaleur pour des cuissons parfaites. La poignée ergonomique reste froide pendant la cuisson pour une manipulation en toute sécurité. Compatible avec tous les types de feux, y compris l'induction, cette casserole deviendra rapidement indispensable dans votre cuisine.",
    features: [
      "Revêtement antiadhésif sans PFOA",
      "Fond triple épaisseur",
      "Compatible induction",
      "Poignée ergonomique",
      "Garantie 5 ans",
    ],
    colors: ["Noir", "Rouge", "Gris anthracite"],
    inStock: true,
  },
  {
    id: "6",
    name: "Set de Couteaux",
    price: "18000 FCFA",
    category: "Ustensiles",
    image: "/placeholder.svg?height=400&width=400",
    description: "Ensemble de couteaux professionnels pour une découpe précise.",
    longDescription:
      "Ce set de couteaux professionnels comprend tous les outils essentiels pour exceller en cuisine. Fabriqués en acier inoxydable de haute qualité, ces couteaux offrent une précision de coupe exceptionnelle et une durabilité à toute épreuve. Les lames parfaitement équilibrées et les manches ergonomiques assurent confort et sécurité lors de l'utilisation. Présentés dans un élégant bloc en bois, ces couteaux apporteront une touche professionnelle à votre cuisine tout en restant à portée de main.",
    features: [
      "Acier inoxydable forgé",
      "Manches ergonomiques",
      "Bloc de rangement inclus",
      "Affûteur intégré",
      "Garantie à vie",
    ],
    inStock: true,
  },
  {
    id: "7",
    name: "Crème Hydratante",
    price: "7500 FCFA",
    category: "Cosmétiques",
    image: "/placeholder.svg?height=400&width=400",
    description: "Crème hydratante enrichie en vitamines pour une peau éclatante.",
    longDescription:
      "Notre crème hydratante est formulée avec un complexe unique de vitamines et d'actifs naturels qui nourrissent intensément la peau. Sa texture légère pénètre rapidement sans laisser de film gras. Enrichie en acide hyaluronique et en vitamine E, elle combat les signes du vieillissement tout en protégeant la peau des agressions extérieures. Utilisée quotidiennement, cette crème révèle l'éclat naturel de votre peau et lui redonne toute sa souplesse. Convient à tous les types de peau, même les plus sensibles.",
    features: [
      "Formule enrichie en vitamines",
      "Hydratation 48h",
      "Sans parabènes",
      "Testée dermatologiquement",
      "Fabrication éco-responsable",
    ],
    colors: ["Standard"],
    inStock: true,
  },
  {
    id: "8",
    name: "Jupe Plissée",
    price: "9000 FCFA",
    category: "Vêtements",
    image: "/placeholder.svg?height=400&width=400",
    description: "Jupe plissée élégante, disponible en plusieurs couleurs.",
    longDescription:
      "Cette jupe plissée élégante est un incontournable de votre garde-robe. Sa coupe mi-longue et ses plis permanents créent un mouvement gracieux à chaque pas. La taille élastiquée offre un confort optimal tout au long de la journée. Confectionnée dans un tissu de qualité qui conserve sa forme même après de nombreux lavages, cette jupe se porte aussi bien avec un t-shirt décontracté qu'avec un chemisier élégant. Polyvalente et intemporelle, elle vous accompagnera saison après saison.",
    features: [
      "Tissu plissé permanent",
      "Taille élastiquée",
      "Doublure intégrée",
      "Lavable en machine",
      "Longueur midi",
    ],
    colors: ["Noir", "Beige", "Bleu marine", "Bordeaux"],
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "9",
    name: "Moule à Gâteau",
    price: "4500 FCFA",
    category: "Ustensiles",
    image: "/placeholder.svg?height=400&width=400",
    description: "Moule à gâteau en silicone pour des pâtisseries parfaites.",
    longDescription:
      "Ce moule à gâteau en silicone alimentaire de haute qualité révolutionnera vos pâtisseries. Flexible et antiadhésif, il permet un démoulage facile et parfait de vos créations. Résistant à des températures allant de -40°C à +230°C, il peut être utilisé au four comme au congélateur. Sa structure renforcée évite les déformations et garantit une cuisson homogène. Facile à nettoyer et peu encombrant, ce moule deviendra rapidement l'allié indispensable de vos moments gourmands.",
    features: [
      "Silicone alimentaire sans BPA",
      "Résistant de -40°C à +230°C",
      "Démoulage facile",
      "Compatible lave-vaisselle",
      "Structure renforcée",
    ],
    colors: ["Rouge", "Bleu", "Vert"],
    inStock: true,
  },
]
